services:
  node:
    image: pasarguard/node:latest # image: ghcr.io/pasarguard/node:latest
    pull_policy: always
    container_name: node
    restart: always
    network_mode: host

    environment:
      SERVICE_PORT: 62050
      SERVICE_PROTOCOL: "grpc"

      SSL_CERT_FILE: "/etc/letsencrypt/live/ses.belbita.online-0001/fullchain.pem"
      SSL_KEY_FILE: "/etc/letsencrypt/live/ses.belbita.online-0001/privkey.pem"
      # api key must be a valid uuid (you can use any version you want)
      API_KEY: "f967f3df-9416-4784-b81a-a93ab6593a83"

      GENERATED_CONFIG_PATH: "/var/lib/pg-node/generated"

      # Xray Paths (defaults usually work)
      XRAY_EXECUTABLE_PATH: "/home/xray_core/xray"
      XRAY_ASSETS_PATH: "/home/xray_core"

    volumes:
      - /var/lib/pg-node:/var/lib/pg-node
      - /etc/letsencrypt/live/ses.belbita.online-0001/fullchain.pem:/etc/letsencrypt/live/ses.belbita.online-0001/fullchain.pem
      - /etc/letsencrypt/live/ses.belbita.online-0001/privkey.pem:/etc/letsencrypt/live/ses.belbita.online-0001/privkey.pem
      - /home/xray_core/xray:/home/xray_core/xray
      - /home/xray_core:/home/xray_core
